Add rhaos-4.14-rhel-8/haproxy-*2.6.13-1.rhaos4.14.el8
These are not built by brew; brew currently fails with:

DEBUG util.py:634:  Error:
DEBUG util.py:634:   Problem 1: package gcc-8.5.0-18.el8.x86_64 requires glibc-devel >= 2.2.90-12, but none of the providers can be installed
DEBUG util.py:634:    - package glibc-devel-2.28-225.el8.x86_64 requires glibc-headers, but none of the providers can be installed
DEBUG util.py:634:    - package glibc-devel-2.28-225.el8.x86_64 requires glibc-headers = 2.28-225.el8, but none of the providers can be installed
DEBUG util.py:634:    - conflicting requests
DEBUG util.py:634:    - nothing provides kernel-headers >= 2.2.1 needed by glibc-headers-2.28-225.el8.x86_64
DEBUG util.py:634:    - nothing provides kernel-headers needed by glibc-headers-2.28-225.el8.x86_64
DEBUG util.py:634:   Problem 2: package gcc-8.5.0-18.el8.x86_64 requires glibc-devel >= 2.2.90-12, but none of the providers can be installed
DEBUG util.py:634:    - package gcc-c++-8.5.0-18.el8.x86_64 requires gcc = 8.5.0-18.el8, but none of the providers can be installed
DEBUG util.py:634:    - package glibc-devel-2.28-225.el8.x86_64 requires glibc-headers, but none of the providers can be installed
DEBUG util.py:634:    - package glibc-devel-2.28-225.el8.x86_64 requires glibc-headers = 2.28-225.el8, but none of the providers can be installed
DEBUG util.py:634:    - conflicting requests
DEBUG util.py:634:    - nothing provides kernel-headers >= 2.2.1 needed by glibc-headers-2.28-225.el8.x86_64
DEBUG util.py:634:    - nothing provides kernel-headers needed by glibc-headers-2.28-225.el8.x86_64
DEBUG util.py:636:  (try to add '--skip-broken' to skip uninstallable packages)
DEBUG util.py:787:  Child return code was: 1

These rpms were built with `rpmbuild -ba haproxy.spec`.